const products = [
    {
        id: 1,
        name: "White Urban Sneaker",
        category: "Shoes",
        price: 43,
        oldPrice: 46,
        discount: 7,
        rating: 5,
        reviews: 12,
        image: "assets/img/product/product1.jpg",
        description: "Comfortable white sneaker perfect for daily wear."
    },
    {
        id: 2,
        name: "Black Street Sneaker",
        category: "Shoes",
        price: 52,
        oldPrice: 60,
        discount: 13,
        rating: 4,
        reviews: 8,
        image: "assets/img/product/product2.jpg",
        description: "Modern black sneaker with street style design."
    },
    {
        id: 3,
        name: "Sport Runner Pro",
        category: "Running",
        price: 75,
        oldPrice: 90,
        discount: 17,
        rating: 5,
        reviews: 21,
        image: "assets/img/product/product3.jpg",
        description: "Lightweight running shoes built for performance."
    },
    {
        id: 4,
        name: "Classic Leather White",
        category: "Shoes",
        price: 68,
        oldPrice: 80,
        discount: 15,
        rating: 4,
        reviews: 14,
        image: "assets/img/product/product4.jpg",
        description: "Premium leather sneakers with classic look."
    },
    {
        id: 5,
        name: "Air Comfort Max",
        category: "Running",
        price: 95,
        oldPrice: 120,
        discount: 21,
        rating: 5,
        reviews: 32,
        image: "assets/img/product/product5.jpg",
        description: "Breathable and flexible running sneakers."
    },
    {
        id: 6,
        name: "Urban Grey Style",
        category: "Casual",
        price: 49,
        oldPrice: 55,
        discount: 11,
        rating: 4,
        reviews: 9,
        image: "assets/img/product/product6.jpg",
        description: "Casual grey sneakers for everyday comfort."
    },
    {
        id: 7,
        name: "Street High Top",
        category: "Casual",
        price: 59,
        oldPrice: 70,
        discount: 16,
        rating: 4,
        reviews: 18,
        image: "assets/img/product/product7.jpg",
        description: "High top sneakers with urban personality."
    },
    {
        id: 8,
        name: "Minimal White Pro",
        category: "Shoes",
        price: 45,
        oldPrice: 50,
        discount: 10,
        rating: 5,
        reviews: 6,
        image: "assets/img/product/product8.jpg",
        description: "Minimal design sneaker with premium comfort."
    },
    {
        id: 9,
        name: "Speed Runner X",
        category: "Running",
        price: 88,
        oldPrice: 105,
        discount: 16,
        rating: 5,
        reviews: 27,
        image: "assets/img/product/product1.jpg",
        description: "Advanced running shoes with superior grip."
    },
    {
        id: 10,
        name: "Daily Comfort Sneaker",
        category: "Casual",
        price: 39,
        oldPrice: 45,
        discount: 13,
        rating: 4,
        reviews: 11,
        image: "assets/img/product/product2.jpg",
        description: "Perfect daily wear sneaker with soft cushioning."
    },
    {
        id: 11,
        name: "Pro Fitness Trainer",
        category: "Training",
        price: 72,
        oldPrice: 85,
        discount: 15,
        rating: 5,
        reviews: 19,
        image: "assets/img/product/product3.jpg",
        description: "Training shoes designed for gym sessions."
    },
    {
        id: 12,
        name: "Street Flex",
        category: "Casual",
        price: 54,
        oldPrice: 65,
        discount: 17,
        rating: 4,
        reviews: 13,
        image: "assets/img/product/product4.jpg",
        description: "Flexible and stylish streetwear sneakers."
    },
    {
        id: 13,
        name: "Ultra Boost Light",
        category: "Running",
        price: 110,
        oldPrice: 130,
        discount: 15,
        rating: 5,
        reviews: 40,
        image: "assets/img/product/product5.jpg",
        description: "High-performance lightweight running shoes."
    },
    {
        id: 14,
        name: "Classic Black Edition",
        category: "Shoes",
        price: 64,
        oldPrice: 75,
        discount: 15,
        rating: 4,
        reviews: 16,
        image: "assets/img/product/product6.jpg",
        description: "Elegant black sneaker for all occasions."
    },
    {
        id: 15,
        name: "Comfort Walk Pro",
        category: "Walking",
        price: 58,
        oldPrice: 70,
        discount: 17,
        rating: 4,
        reviews: 22,
        image: "assets/img/product/product7.jpg",
        description: "Walking shoes with enhanced arch support."
    },
    {
        id: 16,
        name: "Urban Night Sneaker",
        category: "Casual",
        price: 47,
        oldPrice: 55,
        discount: 15,
        rating: 4,
        reviews: 10,
        image: "assets/img/product/product8.jpg",
        description: "Dark edition sneaker for night city vibes."
    },
    {
        id: 17,
        name: "Power Gym Trainer",
        category: "Training",
        price: 69,
        oldPrice: 82,
        discount: 16,
        rating: 5,
        reviews: 24,
        image: "assets/img/product/product1.jpg",
        description: "Durable and stable gym training shoes."
    },
    {
        id: 18,
        name: "Active Run Plus",
        category: "Running",
        price: 92,
        oldPrice: 110,
        discount: 16,
        rating: 5,
        reviews: 29,
        image: "assets/img/product/product2.jpg",
        description: "Premium running shoes with extra cushioning."
    },
    {
        id: 19,
        name: "Street Casual Basic",
        category: "Casual",
        price: 41,
        oldPrice: 48,
        discount: 14,
        rating: 4,
        reviews: 7,
        image: "assets/img/product/product3.jpg",
        description: "Simple casual sneakers for daily style."
    },
    {
        id: 20,
        name: "Elite Performance Pro",
        category: "Running",
        price: 120,
        oldPrice: 145,
        discount: 17,
        rating: 5,
        reviews: 50,
        image: "assets/img/product/product4.jpg",
        description: "Top-tier performance sneakers for athletes."
    }
];